// Generated by CoffeeScript 1.6.3
(function() {
  define(["backbone", "marionette"], function(Backbone, Marionette) {
    var app;
    app = new Marionette.Application();
    app.addRegions({
      header: "#header",
      main: "#main",
      footer: "#footer"
    });
    app.on("initialize:after", function() {
      if (Backbone.history) {
        return Backbone.history.start();
      }
    });
    return app;
  });

}).call(this);
