// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", "marionette", "./views", "ctrlVent", "../gallery/index", "entities/icon"], function(App, Marionette, Views, ctrlVent, Gallery) {
    var Router, controller, icons, router, _ref;
    icons = ctrlVent.reqres.request("icon:entities");
    Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Router.prototype.appRoutes = {
        "home": "showHome",
        "gallery": "showGallery"
      };

      return Router;

    })(Marionette.AppRouter);
    controller = {
      showGallery: function() {
        return Gallery.showGallery();
      },
      showHome: function() {
        var contentView;
        contentView = new Views.ContentView({
          collection: icons
        });
        return App.main.show(contentView);
      }
    };
    router = new Router({
      controller: controller
    });
    ctrlVent.events.on("icon:clicked", function(fragment) {
      return router.navigate(fragment, {
        trigger: true
      });
    });
    return controller;
  });

}).call(this);
