// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./controller"], function(App, Controller) {
    App.module("Home", function(Home, App, Backbone, Marionette, $, _) {
      var API;
      API = {
        showHome: function() {
          return Controller.showHome();
        }
      };
      return Home.on("start", function() {
        return API.showHome();
      });
    });
    return App.Home;
  });

}).call(this);
