// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./views"], function(App, Views) {
    return {
      appendSlider: function() {
        var sliderView;
        sliderView = this.getSliderView();
        return App.slider.show(sliderView);
      },
      getSliderView: function() {
        return new Views.SliderView;
      }
    };
  });

}).call(this);
