// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./views", "ctrlVent", "entities/slider"], function(App, Views, ctrlVent) {
    var images;
    images = ctrlVent.reqres.request("slider:entities");
    return {
      appendSlider: function() {
        var sliderView;
        sliderView = this.getSliderView();
        return App.slider.show(sliderView);
      },
      getSliderView: function() {
        return new Views.SliderView({
          collection: images
        });
      }
    };
  });

}).call(this);
