// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./controller", "bootstrap"], function(App, Controller) {
    App.module("Slider", function(Slider, App, Backbone, Marionette, $, _) {
      var API;
      API = {
        appendSlider: function() {
          return Controller.appendSlider();
        },
        showSlider: function() {
          return $("#slider-modal").modal("show");
        }
      };
      Slider.showSlider = API.showSlider;
      return Slider.on("start", function() {
        return API.appendSlider();
      });
    });
    return App.Slider;
  });

}).call(this);
