// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./controller", "ctrlVent", "entities/footer"], function(App, Controller, ctrlVent) {
    App.module("Footer", function(Footer, App, Backbone, Marionette, $, _) {
      var API, footers;
      footers = ctrlVent.reqres.request("footer:entities");
      API = {
        showFooter: function() {
          return Controller.showFooter(footers);
        }
      };
      return Footer.on("start", function() {
        return API.showFooter();
      });
    });
    return App.Footer;
  });

}).call(this);
