// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["app", "marionette", "text!./tpl/footer.html", "text!./tpl/footer-item.html"], function(App, Marionette, footerTpl, footerItemTpl) {
    var FooterItemView, FooterView, _ref, _ref1;
    return {
      FooterItemView: FooterItemView = (function(_super) {
        __extends(FooterItemView, _super);

        function FooterItemView() {
          _ref = FooterItemView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        FooterItemView.prototype.template = _.template(footerItemTpl, null, {
          variable: "data"
        });

        FooterItemView.prototype.tagName = "li";

        return FooterItemView;

      })(Marionette.ItemView),
      FooterView: FooterView = (function(_super) {
        __extends(FooterView, _super);

        function FooterView() {
          _ref1 = FooterView.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        FooterView.prototype.template = _.template(footerTpl);

        FooterView.prototype.className = "container";

        FooterView.prototype.itemView = FooterItemView;

        FooterView.prototype.itemViewContainer = ".footer-list";

        return FooterView;

      })(Marionette.CompositeView)
    };
  });

}).call(this);
