// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "./controller", "ctrlVent", "entities/header", "../about/index"], function(App, Controller, ctrlVent) {
    App.module("Header", function(Header, App, Backbone, Marionette, $, _) {
      var API, abouts, headers;
      headers = ctrlVent.reqres.request("header:entities");
      abouts = ctrlVent.reqres.request("about:entities");
      API = {
        showNavbar: function() {
          return Controller.showNavbar(headers, abouts);
        }
      };
      return Header.on("start", function() {
        return API.showNavbar();
      });
    });
    return App.Header;
  });

}).call(this);
