// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "ctrlVent"], function(Backbone, ctrlVent) {
    var API, HeaderCollection, _ref;
    HeaderCollection = (function(_super) {
      __extends(HeaderCollection, _super);

      function HeaderCollection() {
        _ref = HeaderCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return HeaderCollection;

    })(Backbone.Collection);
    ctrlVent.reqres.setHandler("header:entities", function() {
      return API.getHeaderEntities();
    });
    ctrlVent.reqres.setHandler("about:entities", function() {
      return API.getAboutEntities();
    });
    return API = {
      getHeaderEntities: function() {
        var headers;
        return headers = new HeaderCollection([
          {
            name: "Home",
            url: "#home"
          }, {
            name: "Blog",
            url: "http://airixly.github.io/"
          }
        ]);
      },
      getAboutEntities: function() {
        var abouts;
        return abouts = new HeaderCollection([
          {
            name: "About",
            url: "#about"
          }
        ]);
      }
    };
  });

}).call(this);
