// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "ctrlVent"], function(Backbone, ctrlVent) {
    var API, SliderCollection, _ref;
    SliderCollection = (function(_super) {
      __extends(SliderCollection, _super);

      function SliderCollection() {
        _ref = SliderCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return SliderCollection;

    })(Backbone.Collection);
    ctrlVent.reqres.setHandler("slider:entities", function() {
      return API.getSliderEntities();
    });
    return API = {
      getSliderEntities: function() {
        var images;
        return images = new SliderCollection([
          {
            name: "Cat",
            url: "dist/img/img_1.jpg"
          }, {
            name: "Sweet",
            url: "dist/img/img_2.jpg"
          }, {
            name: "Sakura",
            url: "dist/img/img_3.jpg"
          }, {
            name: "Strawberry Cake",
            url: "dist/img/img_4.jpg"
          }
        ]);
      }
    };
  });

}).call(this);
