// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "marionette", "./controller", "ctrlVent", "entities/gallery"], function(App, Marionette, Controller, ctrlVent) {
    var API, gallery;
    gallery = ctrlVent.reqres.request("gallery:entities");
    return API = {
      showGallery: function() {
        Controller.showGallery(gallery);
        return ctrlVent.events.trigger("search:gallery");
      }
    };
  });

}).call(this);
