// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette", "text!./tpl/about-tpl.html"], function(Marionette, aboutTpl) {
    var AboutView, _ref;
    return {
      AboutView: AboutView = (function(_super) {
        __extends(AboutView, _super);

        function AboutView() {
          _ref = AboutView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        AboutView.prototype.template = _.template(aboutTpl);

        AboutView.prototype.className = "container about-content";

        return AboutView;

      })(Marionette.ItemView)
    };
  });

}).call(this);
